# Generated by Django 3.0.4 on 2021-06-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_num', models.CharField(max_length=100)),
                ('counter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yes', models.IntegerField()),
                ('no', models.IntegerField()),
                ('husband', models.IntegerField()),
                ('parents', models.IntegerField()),
                ('others', models.IntegerField()),
                ('one', models.IntegerField()),
                ('father', models.IntegerField()),
                ('physical', models.IntegerField()),
                ('psychologically', models.IntegerField()),
                ('both', models.IntegerField()),
                ('violated', models.IntegerField()),
                ('answer1', models.IntegerField()),
                ('answer2', models.IntegerField()),
                ('answer3', models.IntegerField()),
                ('answer4', models.IntegerField()),
                ('city', models.IntegerField()),
                ('countryside', models.IntegerField()),
                ('single', models.IntegerField()),
                ('married', models.IntegerField()),
                ('divorced', models.IntegerField()),
                ('widow', models.IntegerField()),
                ('illiterate', models.IntegerField()),
                ('read', models.IntegerField()),
                ('middle', models.IntegerField()),
                ('high', models.IntegerField()),
                ('educated', models.IntegerField()),
                ('uneducated', models.IntegerField()),
                ('zerotothree', models.IntegerField()),
                ('threetofive', models.IntegerField()),
                ('fivetoseven', models.IntegerField()),
                ('morethan', models.IntegerField()),
                ('physicalviolence', models.IntegerField()),
                ('psychologicalviolence', models.IntegerField()),
                ('verbalviolence', models.IntegerField()),
                ('otherviolence', models.IntegerField()),
            ],
        ),
    ]
